employee/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.display_employee_list, name="employees"),
    path('create/', views.employee_create, name="create"),
    path('details/<int:id>/', views.employee_details, name="details"),
    path('edit/<int:id>/', views.employee_edit, name="edit"),
    path('delete/<int:id>/', views.employee_delete, name="delete"),
]

internal_jobs/urls.py
from django.urls import path, include
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.requirement_list, name="jobs"),
    path('create/', views.requirement_create, name="add"),
    path('details/<int:id>/', views.requirement_details, name="details"),
    path('edit/<int:id>/', views.requirement_edit, name="edit"),
    path('delete/<int:id>/', views.requirement_delete, name="delete"),
    path('reports/', views.job_reports, name="reports"),
    path('applicants/', views.display_job_applications, name="job_applications"),
    path('applicants/create', views.create_applicant, name="applicant_create"),
    path('applicants/edit/<int:id>/', views.edit_applicant, name="applicant_edit"),
    path('applicants/delete/<int:id>/', views.delete_applicant, name="applicant_delete"),
    path('applicants/apply/<str:request_id>', views.apply_to_job, name="apply_job"),

]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from web_templates.views import welcome, user_login, user_logout, signup, change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome, name="welcome"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    path('change_password/', change_password, name="change_password"),
    path('jobs/', include('internal_jobs.urls')),
    path('employees/', include('employee.urls')),
]

web_templates/models.py
from django.db import models

# Create your models here.

web_templates/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.core.checks import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages


@login_required(login_url='login')
def welcome(request):
    return render(request, "web_templates/welcome.html")


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    return HttpResponseRedirect("Account Disabled")
    else:
        form = AuthenticationForm()
    return render(request, "web_templates/login.html", context={"form": form})


@login_required(redirect_field_name='login')
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return HttpResponseRedirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'web_templates/signup.html', {'form': form})


@login_required(login_url='login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'web_templates/change_password.html', {'form': form})

web_templates/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'web_templates/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web_templates/css/mdb.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

</head>
<style>

div.dataTables_length {
    float:right;
}

div.dataTables_filter {
    float: right;
}

div.dataTables_info {
    float: left;
}

div.dataTables_paginate {
    float: right;
}

div.DTTT {
    float: left;
    margin-right: 50px;
}

div.buttons {
    clear: both;
}
</style>
<body>
<nav class="mb-1 navbar navbar-expand-lg navbar-dark purple-gradient font-weight-bold z-depth-1">
  <a class="navbar-brand" href="#">HR Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
        {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'employees'%}">Employees</a>
          </li>
        {% endif %}{% endif %}

        {% if not user.is_superuser %}
        {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'jobs:jobs' %}">Internal Jobs</a>
            </li>
        {% endif %}{% endif %}

        {% if user.is_authenticated %}
        {% if user.is_superuser %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">Internal Jobs
            </a>
            <div class="dropdown-menu dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                <a class="dropdown-item" href="{% url 'jobs:jobs' %}">Show Jobs</a>
                <a class="dropdown-item" href="{% url 'jobs:add' %}">Post New Job</a>
                <a class="dropdown-item" href="{% url 'jobs:job_applications' %}">Show Job Applicants</a>
                <a class="dropdown-item" href="#">Approve</a>
                <a class="dropdown-item" href="{% url 'jobs:reports' %}">Reports</a>
            </div>
          </li>
        {% endif %}{% endif %}
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-user"></i>
            {% if user.is_authenticated  %}
                {{user}}
            {%endif%}
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
            {% if user.is_authenticated %}
                <a class="dropdown-item" href="{% url 'logout' %}">Log Off</a>
                <a class="dropdown-item" href="{% url 'change_password' %}">Change Password</a>
            {% else %}
                <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                <a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a>
            {% endif%}
        </div>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{% static 'web_templates/js/custom.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.colVis.min.js"></script>


</body>
</html>