employee/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.display_employee_list, name="employees"),
    path('create/', views.employee_create, name="create"),
    path('details/<int:id>/', views.employee_details, name="details"),
    path('edit/<int:id>/', views.employee_edit, name="edit"),
    path('delete/<int:id>/', views.employee_delete, name="delete"),
]

internal_jobs/urls.py
from django.urls import path, include
from . import views

app_name = 'jobs'
urlpatterns = [
    path('', views.requirement_list, name="jobs"),
    path('create/', views.requirement_create, name="add"),
    path('details/<int:id>/', views.requirement_details, name="details"),
    path('edit/<int:id>/', views.requirement_edit, name="edit"),
    path('delete/<int:id>/', views.requirement_delete, name="delete"),
    path('reports/', views.job_reports, name="reports"),
    path('applicants/', views.display_job_applications, name="job_applications"),
    path('applicants/create', views.create_applicant, name="applicant_create"),
    path('applicants/edit/<int:id>/', views.edit_applicant, name="applicant_edit"),
    path('applicants/delete/<int:id>/', views.delete_applicant, name="applicant_delete"),
    path('applicants/apply/<str:request_id>', views.apply_to_job, name="apply_job"),

]

job_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from web_templates.views import welcome, user_login, user_logout, signup, change_password

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', welcome, name="welcome"),
    path('login/', user_login, name="login"),
    path('logout/', user_logout, name="logout"),
    path('signup/', signup, name="signup"),
    path('change_password/', change_password, name="change_password"),
    path('jobs/', include('internal_jobs.urls')),
    path('employees/', include('employee.urls')),
]

internal_jobs/models.py
from django.db import models
import datetime

loc = (('Bangalore', 'Bangalore'), ('Noida', 'Noida'))
division = (('SP & T', 'SP & T'), ('Managed Services', 'Managed Services'),('Managed Services', 'Managed Services'))
stat = (('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Joined', 'Joined'))


class JobRequirement(models.Model):
    request_id = models.CharField(max_length=10)
    division = models.CharField(max_length=30, choices=division)
    experience = models.IntegerField()
    designation = models.CharField(max_length=50)
    date_posted = models.DateField()
    date_expiry = models.DateField()
    location = models.CharField(max_length=20, choices=loc)
    skills = models.CharField(max_length=500)
    job_description = models.TextField()

    def __str__(self):
        return f"{self.request_id}"


class JobApplicant(models.Model):
    employee_name = models.CharField(max_length=50)
    employee_id = models.CharField(max_length=15)
    current_level = models.IntegerField()
    current_designation = models.CharField(max_length=50)
    current_division = models.CharField(max_length=20, choices=division)
    skills = models.CharField(max_length=500)
    reporting_manager = models.CharField(max_length=100)
    reporting_lead = models.CharField(max_length=100)
    current_project = models.CharField(max_length=200)
    duration_in_current_Level = models.FloatField(max_length=20)
    last_promotion_if_any_and_when = models.CharField(max_length=300)
    job_id = models.ForeignKey(JobRequirement, on_delete=models.CASCADE)
    date_applied = models.DateField()
    status = models.CharField(max_length=20, choices=stat)

    def __str__(self):
        return f"{self.employee_name} applied to job {self.job_id} on {self.date_applied}"

internal_jobs/forms.py
from django.forms import ModelForm, DateInput
from .models import JobRequirement, JobApplicant


class BaseForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class JobRequirementForm(BaseForm):
    class Meta:
        model = JobRequirement
        fields = "__all__"
        widgets = {
            'date_posted': DateInput(attrs={'type': 'date'}),
            'date_expiry': DateInput(attrs={'type': 'date'})
        }


class JobApplicantForm(BaseForm):
    class Meta:
        model = JobApplicant
        fields = "__all__"
        exclude = ('status',)
        widgets = {
            'date_applied': DateInput(attrs={'type': 'date'})
        }

internal_jobs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, _get_queryset
from django.views.decorators.http import require_POST

from .forms import JobRequirementForm, JobApplicantForm
from .models import JobRequirement, JobApplicant


@login_required(login_url='login')
def requirement_list(request):
    requirements = JobRequirement.objects.all()
    return render(request, "internal_jobs/requirement_list.html", {"requirements": requirements})


@login_required(login_url='login')
def requirement_create(request):
    if request.method == "POST":
        requirement_form = JobRequirementForm(request.POST)
        if requirement_form.is_valid():
            requirement_form.save()
            return redirect("jobs:jobs")
    else:
        requirement_form = JobRequirementForm()
    return render(request, "internal_jobs/create.html", {"requirement_form": requirement_form})


@login_required(login_url='login')
def requirement_edit(request, id):
    jobs = get_object_or_404(JobRequirement, pk=id)
    if request.method == "POST":
        jobs_form = JobRequirementForm(request.POST, instance=jobs)
        if jobs_form.is_valid():
            jobs_form.save()
            return redirect("jobs:jobs")
        else:
            jobs_form = JobRequirementForm(instance=jobs)
            return render(request, "internal_jobs/edit.html", {"requirement_form": jobs_form})
    else:
        jobs_form = JobRequirementForm(instance=jobs)
        return render(request, "internal_jobs/edit.html", {"requirement_form": jobs_form})


@login_required(login_url='login')
def requirement_details(request, id):
    job = get_object_or_404(JobRequirement, pk=id)
    return render(request, "internal_jobs/details.html", {"job": job})


@login_required(login_url='login')
def requirement_delete(request, id):
    job_id = int(id)
    try:
        job_sel = get_object_or_404(JobRequirement, pk=job_id)
    except JobRequirement.DoesNotExist:
        return redirect('jobs:jobs')
    job_sel.delete()
    return redirect('jobs:jobs')


@login_required(login_url='login')
def display_job_applications(request):
    job_applications = JobApplicant.objects.all()
    return render(request, "internal_jobs/job_applications.html", {"job_applications": job_applications})


@login_required(login_url='login')
def create_applicant(request):
    if request.method == "POST":
        job_form = JobApplicantForm(request.POST)
        if job_form.is_valid():
            job_form.save()
            return redirect("jobs:job_applications")
    else:
        job_form = JobApplicantForm()
    return render(request, "internal_jobs/create_applicant.html", {"job_form": job_form})


@login_required(login_url='login')
def edit_applicant(request, id):
    applicant = get_object_or_404(JobApplicant, pk=id)
    if request.method == "POST":
        job_form = JobApplicantForm(request.POST, instance=applicant)
        if job_form.is_valid():
            job_form.save()
            return redirect("jobs:jobs")
        else:
            job_form = JobApplicantForm(instance=applicant)
            return render(request, "internal_jobs/edit_applicant.html", {"job_form": job_form})
    else:
        job_form = JobApplicantForm(instance=applicant)
        return render(request, "internal_jobs/edit_applicant.html", {"job_form": job_form})


@login_required(login_url='login')
def delete_applicant(request):
    return render(request, "requirements/job_applications.html")


def apply_to_job(request, request_id):
    if request.method == "POST":
        job_form = JobApplicantForm(request.POST)
        if job_form.is_valid():
            job_form.save()
            return redirect("jobs:job_applications")
    else:
        job_form = JobApplicantForm()
    return render(request, "internal_jobs/create_applicant.html", {"job_form": job_form})


def job_reports(request):
    return render(request, "internal_jobs/reports.html")

internal_jobs/templates/internal_jobs/create.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Add New Job</h5>
      </div>
<br>
<form method="post">{% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
               <label for="request_id">Request ID</label>
                {{ requirement_form.request_id }}
                {{ requirement_form.request_id.errors }}
            </div>
           <div class="col-sm-3 column-height mb-4">
               <label for="division">Division</label>
                {{ requirement_form.division }}
                {{ requirement_form.division.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="designation">Designation</label>
                {{ requirement_form.designation }}
                {{ requirement_form.designation.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="experience">Experience</label>
                {{ requirement_form.experience }}
                {{ requirement_form.experience.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="gender">Location</label>
                {{ requirement_form.location }}
                {{ requirement_form.location.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_posted">Date Posted</label>
               {{ requirement_form.date_posted }}
                {{ requirement_form.date_posted.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_expiry">Job Expiration Date</label>
               {{ requirement_form.date_expiry }}
                {{ requirement_form.date_expiry.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-12 column-height mb-4">
               <label for="skills">Skills</label>
                {{ requirement_form.skills }}
                {{ requirement_form.skills.errors }}
            </div>
            <div class="col-sm-12 column-height mb-4">
               <label for="address">Job Description</label>
                {{ requirement_form.job_description }}
                {{ requirement_form.job_description.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
                <input type="submit" name="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
    </form>

{% endblock %}

internal_jobs/templates/internal_jobs/create_applicant.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Apply Job</h5>
      </div>
<br>
<form method="post">{% csrf_token %}
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
               <label for="employee_id">Employee ID</label>
                {{ job_form.employee_id }}
                {{ job_form.employee_id.errors }}
            </div>
           <div class="col-sm-3 column-height mb-4">
               <label for="employee_name">Employee Name</label>
                {{ job_form.employee_name }}
                {{ job_form.employee_name.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="current_designation">Current Designation</label>
                {{ job_form.current_designation }}
                {{ job_form.current_designation.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="current_level">Current Level</label>
                {{ job_form.current_level }}
                {{ job_form.current_level.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="current_division">Current Division</label>
                {{ job_form.current_division }}
                {{ job_form.current_division.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="current_project">Current Project</label>
                {{ job_form.current_project }}
                {{ job_form.current_project.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
                <label for="reporting_lead">Reporting Lead</label>
                {{ job_form.reporting_lead }}
                {{ job_form.reporting_lead.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="reporting_manager">Reporting Manager</label>
                {{ job_form.reporting_manager }}
                {{ job_form.reporting_manager.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="duration_in_current_Level">Duration in current level</label>
                {{ job_form.duration_in_current_Level }}
                {{ job_form.duration_in_current_Level.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="last_promotion_if_any_and_when">Last Promotion if any and when</label>
                {{ job_form.last_promotion_if_any_and_when }}
                {{ job_form.last_promotion_if_any_and_when.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_applied">Date</label>
                {{ job_form.date_applied }}
                {{ job_form.date_applied.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="job_id">Job Id</label>
                {{ job_form.job_id }}
                {{ job_form.job_id.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-12 column-height mb-4">
               <label for="skills">Skills</label>
                {{ job_form.skills }}
                {{ job_form.skills.errors }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
                <input type="submit" name="submit" class="btn btn-primary" />
            </div>
        </div>
    </form>



{% endblock %}

internal_jobs/templates/internal_jobs/details.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Job Details</h5>
      </div>
<br>
<form>
    <fieldset>
       <div class="col-sm-4 column-height">
           <label><b>Request ID: </b></label> {{job.request_id}}
       </div>
       <div class="col-sm-4 column-height">
           <label><b>Division: </b></label> {{job.division}}
       </div>
        <div class="col-sm-4 column-height">
           <label><b>Expertise: </b></label> {{job.expertise}}
       </div>

        <div class="col-sm-6 column-height">
           <label><b>Experience: </b></label> {{job.experience}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Designation: </b></label> {{job.designation}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Location: </b></label> {{job.location}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Date Posted: </b></label> {{job.date_posted}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Job Expiry Date: </b></label> {{job.expiry_date}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Skill: </b></label> {{job.skills}}
       </div>
        <div class="col-sm-6 column-height">
           <label><b>Job Description: </b></label>
            {{job.job_description}}
       </div>

    </fieldset>
</form>


{% endblock %}

internal_jobs/templates/internal_jobs/edit.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Edit Job</h5>
      </div>
<br>
<form method="post">{% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
               <label for="request_id">Request ID</label>
                {{ requirement_form.request_id }}
                {{ requirement_form.request_id.errors }}
            </div>
           <div class="col-sm-3 column-height mb-4">
               <label for="division">Division</label>
                {{ requirement_form.division }}
                {{ requirement_form.division.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="designation">Designation</label>
                {{ requirement_form.designation }}
                {{ requirement_form.designation.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="status">Experience</label>
                {{ requirement_form.experience }}
                {{ requirement_form.experience.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="gender">Location</label>
                {{ requirement_form.location }}
                {{ requirement_form.location.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_posted">Date Posted</label>
               {{ requirement_form.date_posted }}
                {{ requirement_form.date_posted.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_expiry">Job Expiration Date</label>
               {{ requirement_form.date_expiry }}
                {{ requirement_form.date_expiry.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-12 column-height mb-4">
               <label for="skills">Skills</label>
                {{ requirement_form.skills }}
                {{ requirement_form.skills.errors }}
            </div>
            <div class="col-sm-12 column-height mb-4">
               <label for="address">Job Description</label>
                {{ requirement_form.job_description }}
                {{ requirement_form.job_description.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
                <input type="submit" name="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
    </form>

{% endblock %}

internal_jobs/templates/internal_jobs/edit_applicant.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Edit Job Application</h5>
      </div>
<br>
<form method="post">{% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
               <label for="employee_id">Employee ID</label>
                {{ job_form.employee_id }}
                {{ job_form.employee_id.errors }}
            </div>
           <div class="col-sm-3 column-height mb-4">
               <label for="employee_name">Employee Name</label>
                {{ job_form.employee_name }}
                {{ job_form.employee_name.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="current_designation">Current Designation</label>
                {{ job_form.current_designation }}
                {{ job_form.current_designation.errors }}
           </div>

            <div class="col-sm-3 column-height mb-4">
               <label for="current_level">Current Level</label>
                {{ job_form.current_level }}
                {{ job_form.current_level.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="current_division">Current Division</label>
                {{ job_form.current_division }}
                {{ job_form.current_division.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="current_project">Current Project</label>
                {{ job_form.current_project }}
                {{ job_form.current_project.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
                <label for="reporting_lead">Reporting Lead</label>
                {{ job_form.reporting_lead }}
                {{ job_form.reporting_lead.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="reporting_manager">Reporting Manager</label>
                {{ job_form.reporting_manager }}
                {{ job_form.reporting_manager.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="duration_in_current_Level">Duration in current level</label>
                {{ job_form.duration_in_current_Level }}
                {{ job_form.duration_in_current_Level.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="last_promotion_if_any_and_when">Last Promotion if any and when</label>
                {{ job_form.last_promotion_if_any_and_when }}
                {{ job_form.last_promotion_if_any_and_when.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="date_applied">Date</label>
                {{ job_form.date_applied }}
                {{ job_form.date_applied.errors }}
           </div>
            <div class="col-sm-3 column-height mb-4">
               <label for="job_id">Job Id</label>
                {{ job_form.job_id }}
                {{ job_form.job_id.errors }}
           </div>
        </div>
        <div class="row">
            <div class="col-sm-12 column-height mb-4">
               <label for="skills">Skills</label>
                {{ job_form.skills }}
                {{ job_form.skills.errors }}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3 column-height mb-4">
                <input type="submit" name="submit" class="btn btn-primary" />
            </div>
        </div>
    </div>
    </form>

{% endblock %}

internal_jobs/templates/internal_jobs/job_applications.html
{% extends "base.html" %}
{% load static %}
{% block title %}Job Applicants{% endblock %}
{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Job Applicants</h5>
      </div>
<br>
<table class="table w-auto" id="applicantsTable">
            <thead>
                <tr >
                    <th scope="col">Employee ID</th>
                    <th scope="col">Employee Name</th>
                    <th scope="col">Skill</th>
                    <th scope="col">Reporting Lead</th>
                    <th scope="col">Reporting Manager</th>
                    <th scope="col">Job Id</th>
                    <th scope="col">Applied Date</th>
                </tr>
            </thead>
            <tbody>
            {% for applicant in job_applications %}
              <tr>
                  <td>{{applicant.employee_id}}</td>
                  <td>{{applicant.employee_name}}</td>
                  <td>{{applicant.skills}}</td>
                  <td>{{applicant.reporting_lead}}</td>
                  <td>{{applicant.reporting_manager}}</td>
                  <td>{{applicant.job_id}}</td>
                  <td>{{applicant.date_applied}}</td>
              </tr>
            </tbody>
            {% endfor %}
    </table>

{% endblock %}

internal_jobs/templates/internal_jobs/requirement_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Internal Jobs{% endblock %}
{% block content %}
<div class="modal-header">
        <h5 class="modal-title">Internal Jobs</h5>
      </div>
<br>
<table class="table w-auto" id="internalJobsTable">
            <thead>
                <tr>
                    <th scope="col">Request ID</th>
                    <th scope="col">Division</th>
                    <th scope="col">Designation</th>
                    <th scope="col">Location</th>
                    <th scope="col">Skill</th>
                    <th scope="col">Date Posted</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            {% for requirement in requirements %}
              <tr >
                  <td>{{requirement.request_id}}</td>
                  <td>{{requirement.division}}</td>
                  <td>{{requirement.designation}}</td>
                  <td>{{requirement.location}}</td>
                  <td>{{requirement.skills}}</td>
                  <td>{{requirement.date_posted}}</td>
                  <td>
                      {% if not user.is_superuser %}
                      {% if user.is_authenticated %}
                            <a href="{% url 'jobs:apply_job' requirement.request_id %}"><i class="fas fa-hand-pointer" data-toggle="tooltip" data-placement="top" title="Job Apply"></i></a>
                      {% endif %}{% endif %}
                      {% if user.is_superuser %}
                        <a href="{% url 'jobs:edit' requirement.id %}"><i class="fas fa-edit" data-toggle="tooltip" data-placement="top" title="Edit Job"></i></a>
                        <a href="{% url 'jobs:details' requirement.id %}"><i class="fas fa-eye" data-toggle="tooltip" data-placement="top" title="Job Details"></i></a>
                        <a href="{% url 'jobs:delete' requirement.id %}"><i class="fas fa-trash" data-toggle="tooltip" data-placement="top" title="Delete Job"></i></a>
<!--                        <a  href="{% url 'jobs:delete' requirement.id %}" data-toggle="modal" data-target="#exampleModal" data-placement="top" title="Delete Job" data-whatever="{% url 'jobs:delete' requirement.id %}"><i class="fas fa-trash"></i></a>-->
                      {% endif %}
                  </td>
              </tr>
            {% endfor %}
            </tbody>
    </table>

<div class="modal" id="exampleModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete Confirmation?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="post">
          <div class="modal-body">
              Do you really want to delete this employee? <br>This process cannot be undone.
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
<!--          <button type="button" class="btn btn-danger">Delete</button>-->
              <a id="delete_id" class="btn btn-danger" href="">Delete</a>
          </div>
      </form>
    </div>
    </div>
  </div>
</div>

<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->

<script type="text/javascript">

</script>

{% endblock %}